db:
  image: mysql:5.7
  ports:
    - "3307:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=db_example

mailhog:
  image: mailhog/mailhog
  container_name: 'mailhog'
  ports:
  - "1025:1025"
  - "8025:8025"